name: heroku docker deploy
description: it's an action to build and deploy a docker file to heroku
inputs:
  heroku_api_key:
    description: "your heroku api key"
    required: true
  heroku_app_name:
    description: "your heroku app name"
    required: true
  formation:
    description: "heroku dyno formation"
    default: "web"
    required: false
  dockerfile_name:
    description: "dockerfile name"
    default: "dockerfile"
    required: false
  dockerfile_path:
    description: "dockerfile path"
    default: ""
    required: false
  docker_options:
    description: "optional build parameters"
    default: ""
    required: false
runs:
  using: "node12"
  main: "index.js"
